### ISSUE TITLE
Self Referencing Document

### ISSUE THREAD

**Issue by han-tyumi** [saiichihashimoto/sanity-typed-schema-builder#114]
Was wondering if I was missing a better way to create a document that references itself.
This is what I currently have which seems pretty overkill.
I have a few ideas for making this a bit simpler in the API if there isn't already a better solution.

```ts
import { s } from "sanity-typed-schema-builder";

const baseCategory: Parameters<typeof s.document>[0] = {
  name: "category",
  fields: [
    {
      name: "name",
      type: s.string(),
    },
    {
      name: "slug",
      type: s.slug({ options: { source: "name" } }),
    },
  ],
};

const category = s.document({
  ...baseCategory,
  fields: [
    ...baseCategory.fields,
    {
      name: "parent",
      type: s.reference({
        to: [s.document(baseCategory)],
      }),
    },
  ],
});

export default category;
```

**Comment by saiichihashimoto** [comment]
Currently, there isn't a solution! What's your idea for a simpler API? The idea I had was to allow schema types to be functions, which would end up allowing a truly recursive self-referencing document:

```diff
const category = s.document({
  ...baseCategory,
  fields: [
    ...baseCategory.fields,
    {
      name: "parent",
      type: s.reference({
-       to: [s.document(baseCategory)],
+       to: [() => category],
      }),
    },
  ],
});
```

It's not my favorite but, without drastically changing the API for this edge case, I think this ends up being the cleanest solution.

**Comment by saiichihashimoto** [comment]
A few issues I'm seeing right off the bat:

- A strong tenant of this library is that the type of _everything_ is inferred; nowhere do you have to specify a type. I don't know how to handle this with a self referencing document: https://twitter.com/shayanhashimoto/status/1546923270309658626
- Mocks are going to get really weird. To mock the document, it needs to mock the reference, which uses the id of the mocked document, which mocks the reference, etc. infinite loop. Not sure how to handle that properly. I might be able to break up mocking the document from mocking its id, so that the reference mocks can resolve.
- I have an (undocumented) feature of "resolving" these types, mainly for mocks. For example, if you make a mock of a document, and then you `docType.resolve(mock)`, it will recursively find the references and replace them with a corresponding mock. This is nice for sanity queries where you expand your references. This will run into a similar problem as the mocks, where it will end up in an infinite loop of mocking.

**Comment by han-tyumi** [comment]
I was also thinking of the same solution of allowing functions to specify a type.
Another idea was to also allow specifying only the required plain object for `to` rather than the full `document`.

But as you said, I can see that there'd be some issues with mocks no matter the solution.
And unfortunately I'm not that familiar with the area, but maybe I'll take a look at some point.

Maybe you could count the number of levels of recursion and have a limit (maybe throw an error)?
And the user could also manually specify the number levels to be mocked?

**Comment by saiichihashimoto** [comment]
Honestly, I don't see how we'd pull this off. Any solution I see is pretty subpar and misses a lot of usecases. I think this is one of those where it's a limitation of typescript we're stuck with.
