### ISSUE TITLE
array() of blocks() are readonly but PortableText requires a mutable value.

### ISSUE THREAD

**Issue by miklschmidt** [saiichihashimoto/sanity-typed-schema-builder#156]
Currently you have to go through some hoops to not get errors.

```typescript
type DeepWriteable<T> = { -readonly [P in keyof T]: DeepWriteable<T[P]> };
return (
    <PortableText value={value as DeepWriteable<typeof value>} components={} />
)
```

Am i doing something wrong, or could we maybe use the `readOnly` prop in the schema to make these mutable in the resulting types?

**Comment by saiichihashimoto** [comment]
I don't remember where in the typing it is, but having this be `readonly` wasn't an intentional decision, but rather a consequence of convenience. It was just easier to produce a `readonly` value somewhere. If you can identify it with a fix, would be happy to accept a PR.

For clarity: returning a `readonly` type is different than the `readOnly` prop, nor should they be the same. The `readOnly` prop is so that the sanity UI doesn't allow editing. Returning a `readonly` type is about immutability in your codebase, which is entirely your own decision. Considering `readOnly` can be a function, it's very clear these refer to entirely different things.

**Comment by miklschmidt** [comment]
I realized that 5 minutes after i posted, still learning sanity, just jumped on it yesterday :)

i’ll see if i can come up with a fix :)

**Comment by miklschmidt** [comment]
Just to be sure, i’m just making the array/block types mutable, or do you want to drop readonly from everything? It sort of makes sense that they’re all readonly, you’re not supposed to mutate them, it just makes it harder to pass them to other code that (maybe incorrectly) don’t expect a readonly type.

**Comment by miklschmidt** [comment]
It's easy enough to just get rid of readonly alltogether, just remove `readonly` from TupleOfLength, and it's gone, everything checks out. But i'm not sure that's what you want, in which case it's slightly more complicated.
